// This is an autogenerated file from running quasar genkit.
'use server';
/**
 * @fileOverview This file defines the Genkit flow for providing AI suggestions
 * for improvements to the generated code based on the original prompt.
 *
 * @exports aiSuggestions
 * @exports AISuggestionsInput
 * @exports AISuggestionsOutput
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AISuggestionsInputSchema = z.object({
  prompt: z.string().describe('The original prompt used to generate the website code.'),
  code: z.string().describe('The generated HTML/CSS/JS code for the website.'),
});
export type AISuggestionsInput = z.infer<typeof AISuggestionsInputSchema>;

const AISuggestionsOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('An array of AI suggestions for improving the website code.'),
});
export type AISuggestionsOutput = z.infer<typeof AISuggestionsOutputSchema>;

export async function aiSuggestions(input: AISuggestionsInput): Promise<AISuggestionsOutput> {
  return aiSuggestionsFlow(input);
}

const aiSuggestionsPrompt = ai.definePrompt({
  name: 'aiSuggestionsPrompt',
  input: {schema: AISuggestionsInputSchema},
  output: {schema: AISuggestionsOutputSchema},
  prompt: `You are an AI expert in web development. Given the original prompt and the generated code, provide a list of suggestions for improving the code.

Original Prompt: {{{prompt}}}

Generated Code:
{{code}}

Suggestions (as a numbered list):`,
});

const aiSuggestionsFlow = ai.defineFlow(
  {
    name: 'aiSuggestionsFlow',
    inputSchema: AISuggestionsInputSchema,
    outputSchema: AISuggestionsOutputSchema,
  },
  async input => {
    const {output} = await aiSuggestionsPrompt(input);
    return output!;
  }
);
